// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	wb_l0 "wb-l0"

	gomock "github.com/golang/mock/gomock"
)

// MockOrder is a mock of Order interface.
type MockOrder struct {
	ctrl     *gomock.Controller
	recorder *MockOrderMockRecorder
}

// MockOrderMockRecorder is the mock recorder for MockOrder.
type MockOrderMockRecorder struct {
	mock *MockOrder
}

// NewMockOrder creates a new mock instance.
func NewMockOrder(ctrl *gomock.Controller) *MockOrder {
	mock := &MockOrder{ctrl: ctrl}
	mock.recorder = &MockOrderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrder) EXPECT() *MockOrderMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockOrder) AddOrder(orderUID wb_l0.Order, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", orderUID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockOrderMockRecorder) AddOrder(orderUID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockOrder)(nil).AddOrder), orderUID, data)
}

// GetOrder mocks base method.
func (m *MockOrder) GetOrder(id string) (wb_l0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", id)
	ret0, _ := ret[0].(wb_l0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderMockRecorder) GetOrder(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrder)(nil).GetOrder), id)
}

// PullAllOrders mocks base method.
func (m *MockOrder) PullAllOrders() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullAllOrders")
	ret0, _ := ret[0].(error)
	return ret0
}

// PullAllOrders indicates an expected call of PullAllOrders.
func (mr *MockOrderMockRecorder) PullAllOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullAllOrders", reflect.TypeOf((*MockOrder)(nil).PullAllOrders))
}
